version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/import-files-by-colders
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres:
  bundler_gems:

  # app:
  #   env_file: .env
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
